### ISSUE TITLE
Does this work on Angular2 Nativescript?

### ISSUE THREAD

**Issue by ezequielzacca** [PeterStaev/NativeScript-Status-Bar#4]
I cant make it work based on the example, it says it cant find the module, could you please provide some code example?

**Comment by PeterStaev** [comment]
Hey @ezequielzacca , when you get an error that it cannot find the module the problem is usually that the newly installed plugin was not copied to the device. Try doing `tns plaform clean ios` or `tns plaform clean android` and then do a full rebuild of the app with `tns run`.

**Comment by jdnichollsc** [comment]
@PeterStaev maybe you can include in the README the following instruction to import this excellent plugin with Angular:
`import * as statusBar from 'nativescript-status-bar'`
