### ISSUE TITLE
Cannot read property "getWindow" of undefined with Nativescript 4.2

### ISSUE THREAD

**Issue by alexandruantonica** [PeterStaev/NativeScript-Status-Bar#7]
I got this error when I try to build the app

```
System.err: com.tns.NativeScriptException:
System.err: Calling js method run failed
System.err:
System.err: TypeError: Cannot read property 'getWindow' of undefined
System.err: File: "file:///data/data/com.tappter.pim/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 155, column: 24
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'hide', file:'file:///data/data/com.tappter.pim/files/app/tns_modules/nativescript-status-bar/status-bar.js', line: 8, column: 37
System.err: 	Frame: function:'TutorialComponent.ngOnInit', file:'file:///data/data/com.tappter.pim/files/app/welcome/tutorial/tutorial.component.js', line: 72, column: 19
```

```
⚠ Update available for component nativescript. Your current version is 4.2.4 and the latest available version is 5.0.1.
⚠ Update available for component tns-core-modules. Your current version is 4.2.1 and the latest available version is 5.0.2.
⚠ Update available for component tns-android. Your current version is 4.2.0 and the latest available version is 5.0.0.
⚠ Update available for component tns-ios. Your current version is 4.2.0 and the latest available version is 5.0.0.
```

**Comment by PeterStaev** [comment]
Hey @alexandruantonica , seems you are using it an angular project, and I'm not sure the plugin works there at all.

**Comment by alexandruantonica** [comment]
@PeterStaev It worked after I updated the project to Nativescript 4.2. 
I've noticed this 
NS 3.4.1 : [public get activity(): android.app.Activity](https://github.com/NativeScript/NativeScript/blob/v3.4.1-archive/tns-core-modules/ui/frame/frame.android.ts#L407)
NS >3.4.1 : [public get activity(): android.support.v7.app.AppCompatActivity](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/frame/frame.android.ts#L582)

And this is the place where I'm stuck because I can't find `getWindow()`.

**Comment by 000panther** [comment]
I made a fix for the issue - you can try it until it is merged in here by installing apolloai-nativescript-status-bar and changing your references in the code to 

`import * as statusBar from 'apolloai-nativescript-status-bar';`
