### ISSUE TITLE
TypeError: Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by SephReed** [PeterStaev/NativeScript-Status-Bar#8]
I get the error: TypeError: Cannot read property 'android' of undefined

**Comment by rafaelcmrj** [comment]
same here

**Comment by 000panther** [comment]
I made a possible fix for the issue - you can try it until it is merged in here by installing apolloai-nativescript-status-bar and changing your references in the code to 

`import * as statusBar from 'apolloai-nativescript-status-bar';`
